#!/bin/bash
#SBATCH --job-name=INHMarkers
#SBATCH -p standard
#SBATCH -A vswarup_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --error=slurm-%J.err
#SBATCH --mem 128G
#SBATCH --array=1-5
#SBATCH --time=4:00:00

source ~/.bashrc
conda activate cicero

# seurat object path:
seurat="/dfs3b/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/data/ADDS_integrated.rds"
outdir="/dfs3b/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/DEGs/subclusters/INH/"
type="markers"
name="subcluster_markers"
cluster="cell_identity"
latent="Batch,nCount_RNA"
subset_col="cell_type"
subset_groups="INH"


mkdir $outdir

# launch R script:
Rscript --vanilla /dfs3b/swaruplab/smorabit/analysis/ADDS_2021/bin/parallel_DEGs.R \
    --seurat $seurat \
    --outdir $outdir \
    --type $type \
    --cluster $cluster \
    --name $name \
    --index $SLURM_ARRAY_TASK_ID \
    --test "MAST" \
    --pos "TRUE" \
    --pct 0.2 \
    --logfc 0.25 \
    --verbose "TRUE" \
    --latent $latent \
    --cores 16 \
    --subset-col=$subset_col \
    --subset-groups=$subset_groups
