#!/bin/bash
#SBATCH --job-name=DXMarkCT
#SBATCH -p standard
#SBATCH -A seyedam_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --error=slurm-%J.err
#SBATCH --mem 128G
#SBATCH --array=1-7
#SBATCH --time=12:00:00

source ~/.bash_profile
conda activate seurat

# TODO
# seurat object path:
seurat="/pub/smorabit/for_fairlie/ADDS/data/ADDS_seurat_sex_downsampled.rds"
outdir="/dfs8/pub/freese/mortazavi_lab/data/ADDS_2021/visium/human_analysis/F_v_M_regions/"
type="conditions"
condition="Sex"
cluster="region"
latent="nCount_Spatial,PMI"

mkdir $outdir

################################################################################
# F vs M
################################################################################

name="F_v_M"
group1="F"
group2="M"

# launch R script:
Rscript --vanilla /dfs8/pub/freese/mortazavi_lab/data/ADDS_2021/parallel_DEGs.R \
  --seurat $seurat \
  --outdir $outdir \
  --type $type \
  --cluster $cluster \
  --condition $condition \
  --name $name \
  --index $SLURM_ARRAY_TASK_ID \
  --group1 $group1 \
  --group2 $group2 \
  --test "MAST" \
  --pos "FALSE" \
  --pct 0 \
  --logfc 0 \
  --verbose "TRUE" \
  --latent $latent \
  --cores 16 \
  --assay "Spatial"
