#!/bin/bash
#SBATCH --job-name=ADci
#SBATCH -p standard
#SBATCH -A vswarup_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --error=slurm-%J.err
#SBATCH --mem 96G
#SBATCH --array=1-30
#SBATCH --time=20:00:00


# job number 15 is going to get killed, need to give it more than 20 hours or just more cores?

source ~/.bashrc
conda activate cicero

# seurat object path:
seurat="/dfs3b/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/data/AD_integrated.rds"
outdir="/dfs3b/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/DEGs/condition/AD_ci/"
type="conditions"
condition="Diagnosis"
name="AD_ci"
cluster="cell_identity"
latent="Study,nCount_RNA"
subset_col="Diagnosis"
subset_groups="AD,Control"
group1="AD"
group2="Control"

mkdir $outdir

# launch R script:
Rscript --vanilla /dfs3b/swaruplab/smorabit/analysis/ADDS_2021/bin/parallel_DEGs.R \
  --seurat $seurat \
  --outdir $outdir \
  --type $type \
  --cluster $cluster \
  --condition $condition \
  --name $name \
  --index $SLURM_ARRAY_TASK_ID \
  --group1 $group1 \
  --group2 $group2 \
  --test "MAST" \
  --pos "FALSE" \
  --pct 0 \
  --logfc 0 \
  --verbose "TRUE" \
  --latent $latent \
  --cores 32 \
  --subset-col=$subset_col \
  --subset-groups=$subset_groups
