#!/bin/bash
#SBATCH --job-name=testmark
#SBATCH -p standard
#SBATCH -A vswarup_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --error=slurm-%J.err
#SBATCH --mem 128G
#SBATCH --array=1-2
#SBATCH --time=18:00:00

source ~/.bashrc
conda activate cicero

# seurat object path:
seurat="/dfs3b/swaruplab/smorabit/analysis/ADDS_2021/splitseq/data/ADDS_integrated_scvi.rds"
outdir="/dfs3b/swaruplab/smorabit/analysis/ADDS_2021/splitseq/DEGs/DSAD_vs_Control_FCX_clusters/"
type="conditions"
condition="DX"
cluster="annotation"
latent="Batch,nCount_RNA,pct_counts_mt,RIN,PMI"
subset_col="Region"
subset_groups="FCX"

mkdir $outdir

################################################################################
# DSAD vs Control
################################################################################

name="DSAD_vs_Control"
group1="DSAD"
group2="Control"

# launch R script:
Rscript --vanilla /dfs3b/swaruplab/smorabit/analysis/ADDS_2021/bin/parallel_DEGs.R \
  --seurat $seurat \
  --outdir $outdir \
  --type $type \
  --cluster $cluster \
  --condition $condition \
  --name $name \
  --index $SLURM_ARRAY_TASK_ID \
  --group1 $group1 \
  --group2 $group2 \
  --test "MAST" \
  --pos "FALSE" \
  --pct 0 \
  --logfc 0 \
  --verbose "TRUE" \
  --latent $latent \
  --cores 32 \
  --subset-col=$subset_col \
  --subset-groups=$subset_groups
