#!/bin/bash
#SBATCH --job-name=split
#SBATCH -p standard
#SBATCH -A mblurton_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --error=slurm-%J.err
#SBATCH --mem 128G
#SBATCH --array=0-7
#SBATCH --time=72:00:00



# activate conda env:
source ~/.bashrc
conda activate splitseq

module load samtools
module load star

cd /dfs3b/swaruplab/smorabit/data/ADDS_2021/

# set data and reference directories
fastqs="./expdata/Batch5/"
ref_dir="./genomes/hg38/"

let index="$SLURM_ARRAY_TASK_ID"

# find current sublibrary
sublibraries=($(ls $fastqs | cut -d '_' -f 1-3 | uniq))
sample=${sublibraries[$index]}
echo $sample

# make output dir for this sample
mkdir ./analysis/Batch5/$sample

splitpipe/split-pipe \
  --mode all \
  --nthreads 32 \
  --genome_dir $ref_dir \
  --fq1 $fastqs$sample"_L004_R1_001.fastq.gz" \
  --fq2 $fastqs$sample"_L004_R2_001.fastq.gz" \
  --output_dir analysis/Batch5/$sample \
  --sample '28' A1-A4 \
  --sample '16' A5-A8 \
  --sample '94' A9-A12 \
  --sample '88' B1-B4 \
  --sample '131' B5-B8 \
  --sample '19' B9-B12 \
  --sample '107' C1-C4 \
  --sample '101' C5-C8 \
  --sample '10' C9-C12 \
  --sample '63' D1-D2 \
  --sample '128' D3-D4 \
  --sample '50' D5-D6 \
  --sample '100' D7-D8 \
  --sample 'humAD-87' D9-D10 \
  --sample '20' D11-D12