#!/bin/bash
#SBATCH --job-name=split
#SBATCH -p standard
#SBATCH -A mblurton_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --error=slurm-%J.err
#SBATCH --mem 200G
#SBATCH --array=4
#SBATCH --time=72:00:00

# conda init bash
# conda activate splitseq

# activate conda env:
source ~/.bashrc
conda activate splitseq

module load samtools
module load star

cd /dfs3b/swaruplab/smorabit/data/ADDS_2021/

# set data and reference directories
fastqs="./expdata/Batch1/"
ref_dir="./genomes/hg38/"

let index="$SLURM_ARRAY_TASK_ID"

# find current sublibrary
sublibraries=($(ls $fastqs | cut -d '_' -f 1-2 | uniq))
sample=${sublibraries[$index]}
echo $sample

# make output dir for this sample
mkdir ./analysis/$sample


splitpipe/split-pipe \
  --mode all \
  --nthreads 32 \
  --genome_dir $ref_dir \
  --fq1 $fastqs$sample"_L004_R1_001.fastq.gz" \
  --fq2 $fastqs$sample"_L004_R2_001.fastq.gz" \
  --output_dir analysis/$sample \
  --sample '24' A1-A2 \
  --sample '86' A3-A4 \
  --sample '28' A5-A6 \
  --sample '10' A7-A8 \
  --sample '34' A9-A10 \
  --sample '63' A11-A12 \
  --sample '52' B1-B2 \
  --sample '97' B3-B4 \
  --sample '82' B5-B6 \
  --sample '128' B7-B8 \
  --sample '134' B9-B10 \
  --sample '69' B11-B12 \
  --sample '104' C1-C2 \
  --sample '66' C3-C4 \
  --sample '83' C5-C6 \
  --sample '54' C7-C8 \
  --sample '26' C9-C10 \
  --sample '31' C11-C12 \
  --sample '16' D1-D2 \
  --sample '129' D3-D4 \
  --sample '115' D5-D6 \
  --sample '50' D7-D8 \
  --sample '7' D9-D10 \
  --sample '94' D11-D12
