#!/bin/bash
#SBATCH --job-name=DxeAD
#SBATCH -p standard
#SBATCH -A vswarup_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --error=slurm-%J.err
#SBATCH --mem 128G
#SBATCH --array=1-7
#SBATCH --time=12:00:00

source ~/.bash_profile
conda activate hdWGCNA

# seurat object path:
seurat="/dfs7/swaruplab/smorabit/analysis/ADDS_2021/visium/human/data/earlyAD_seurat_sex_downsampled.rds"
outdir="/dfs7/swaruplab/smorabit/analysis/ADDS_2021/visium/human/DEGs/data/F_vs_M_regions_earlyAD"
type="conditions"
condition="Sex"
cluster="region"
latent="Sample,nCount_Spatial,PMI"

mkdir $outdir

################################################################################
# F vs M
################################################################################

name="F_v_M"
group1="F"
group2="M"

# launch R script:
Rscript --vanilla /dfs7/swaruplab/smorabit/analysis/ADDS_2021/bin/parallel_DEGs.R \
  --seurat $seurat \
  --outdir $outdir \
  --type $type \
  --cluster $cluster \
  --condition $condition \
  --name $name \
  --index $SLURM_ARRAY_TASK_ID \
  --group1 $group1 \
  --group2 $group2 \
  --test "MAST" \
  --pos "FALSE" \
  --pct 0 \
  --logfc 0 \
  --verbose "TRUE" \
  --latent $latent \
  --cores 32 \
  --assay "Spatial"
