#!/bin/bash
#SBATCH --job-name=scDRS
#SBATCH -p standard
#SBATCH -A vswarup_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --error=slurm-%J.err
#SBATCH --mem 128G
#SBATCH --array=0-73
#SBATCH --time=18:00:00

source ~/.bashrc
conda activate scanpy

# anndata
h5ad_file="/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/scDRS/data/Mathys_2019_scDRS.h5ad"
h5ad_species="hsapiens"
cov_file="/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/scDRS/data/Mathys_2019_scDRS_cov.tsv"

# get array of all samples
samples=($(ls $input_dir | uniq))

# gene set to test
gs_species="hsapiens"
gs_dir="/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/scDRS/data/scdrs_data/gs_file/individual/"
gs_files=($(ls $gs_dir | uniq))

# current sample based on SLURM index
let index="$SLURM_ARRAY_TASK_ID"
gs_file=${gs_files[$index]}
gs_file=$gs_dir/$gs_file
echo $gs_file

# output folder
out_dir="/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/scDRS/data/outputs/Mathys_2019/"

scdrs compute-score \
    --h5ad-file $h5ad_file \
    --h5ad-species $h5ad_species \
    --gs-file $gs_file \
    --gs-species $gs_species \
    --out-folder $out_dir \
    --cov-file $cov_file \
    --flag-filter-data True\
    --flag-raw-count True\
    --n-ctrl 1000\
    --flag-return-ctrl-raw-score False\
    --flag-return-ctrl-norm-score True

