```{r eval=FALSE}

library(Seurat)
#library(tidyverse)
library(dplyr)
library(ggplot2)
library(cowplot)
library(Matrix)
library(viridis)
library(harmony)
library(ggpubr)
library(patchwork)
library(RColorBrewer)
library(ggrepel)
library(CellTrek)
library(hdWGCNA)

#source("/pub/smorabit/hdWGCNA/bin/spatial_functions.R")
source('/dfs7/swaruplab/smorabit/analysis/scWGCNA/bin/spatial_functions.R')


# 2,000 MB limit:
options(future.globals.maxSize= 2000*1024^2)


setwd("/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/spatial_mapping/")

fig_dir <- "figures/"
data_dir <- "data/"


# load visium & split-seq seurat objects:
seurat_vis <- readRDS('/dfs7/swaruplab/smorabit/analysis/ADDS_2021/visium/human/data/ADDS_seurat_processed.rds')

# seurat_obj <- readRDS("/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/data/ADDS_integrated_scvi.rds")

# load ADDS dataset:
seurat_obj <- readRDS(file="/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/data/ADDS_integrated.rds" )

# only get the FCX:
seurat_obj <- subset(seurat_obj, Tissue != 'PCC')

# saveRDS(seurat_obj, file="/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/data/ADDS_integrated_FCX.rds")

# add barcode:
seurat_obj$bc <- colnames(seurat_obj)
seurat_vis$bc <- colnames(seurat_vis)

var_df <- read.delim(file = "/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/data/ADDS_subclusters_var.tsv", sep='\t')

VariableFeatures(seurat_obj) <- var_df$X



# representative samples
human_rep_samples <- c(
  'Dec_13_2021_Human5', 'Dec_20_2021_Human1',
  'Dec_13_2021_Human6', 'Oct_2021_6',
  'Dec_13_2021_Human3', 'Dec_13_2021_Human7',
  'Nov_24_2021_VisiumHuman_12', 'Dec_13_2021_Human8'
)

#################################################################
# Load color schemes
#################################################################


human_cp <- c(
      "L1" = "#8B3D5A", "L2-3" = "#E7BDE1", "L3-4" = "#E6A4CD",
      "L3-4-5" = "#CF8BA3", "L5-6" = "#9E6D7F", "L6b" = "#CDAEB9", "WM1" = "#64BCDB", "WM2" = "#62A7D7", "WM3" = "#99C8D7")


# color scheme:
color_df <- read.csv(file='/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/data/cell_identity.csv')
color_df <- color_df[,2:3]

group_levels <- c(
  'EX L2', 'EX L2-3', 'EX L3-5', 'EX L5', 'EX L5-6', 'EX L6',
  'INH VIP+', 'INH', 'INH LAMP5+', 'INH PVALB+', 'INH SST+',
  'ASC1', 'ASC2', 'ASC3', 'ASC4',
  'MG1', 'MG2',
  'ODC1', 'ODC2', 'ODC3',
  'OPC1', 'OPC2', 'OPC3',
  'END Arterial', 'END Capillary',
  'T-Pericyte', 'M-Pericyte', 'SMC',
  'Perivascular Fibroblast', 'Meningeal Fibroblast'
)
color_df$group <- factor(as.character(color_df$group), levels=group_levels)
color_df <- arrange(color_df, group)
cp <- as.character(color_df$colour)
names(cp) <- as.character(color_df$group)



st_color_df <- data.frame(
  colour = as.character(human_cp),
  group = names(human_cp)
)
st_color_df$group <- factor(as.character(st_color_df$group), levels=names(human_cp))


seurat_obj$cell_identity <- factor(
  as.character(seurat_obj$cell_identity),
  levels = group_levels
)


#################################################################
# Load celltrek coordinates:
#################################################################

anno_df <- read.csv('celltrek_coords_combined.csv')

```

Load the scDRS results 

```{r eval=FALSE}

seurat_integrated <- readRDS("/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/integration/data/ADDS_AD_integrated.rds")

scdrs <- read.table("../scDRS/data//PASS_Alzheimers_Jansen2019.score")

ix <- match(as.character(seurat_integrated$bc), rownames(scdrs))
scdrs <- scdrs[ix,]
all.equal(as.character(seurat_integrated$bc), rownames(scdrs))

seurat_mg$scdrs_zscore <- scdrs_df$zscore

table(rownames(scdrs) %in% colnames(seurat_integrated))

tmp  <- stringr::str_sub(rownames(scdrs), end=-3)

ix <- match(colnames(seurat_obj), tmp)
scdrs <- scdrs[ix,]
all.equal(colnames(seurat_obj), tmp[ix])

seurat_obj$scdrs_zscore <- scdrs$zscore
seurat_obj$scdrs_normscore <- scdrs$norm_score
seurat_obj$pval <- scdrs$pval
seurat_obj$mv_pcal <- scdrs$mc_pval


p <- VlnPlot(seurat_obj, features = 'scdrs_zscore', group.by = 'cell_identity', split.by='Diagnosis',  pt.size=0) + NoLegend()

pdf(paste0(fig_dir, 'test_scdrs.pdf'), width=10, height=4)
p
dev.off()



p <- FeatureEmbedding(
  seurat_obj,
  features='scdrs_normscore',
  same_range=FALSE,
  #ncol=4,
  #plot_max='q99',
  #plot_min=0,
  dpi=200,
  point_size=1,
  dpi_scale=0.5,
  order_points=TRUE,
  colfunc=viridis::magma,
  combine=FALSE
)


p <- p + scale_color_gradient2()


pdf(paste0(fig_dir, 'test_scdrs_featureplot.pdf'), width=9, height=9)
p
dev.off()


```


```{r eval-FALSE}



cur_vis_sample <- 'Dec_13_2021_Human8'
cur_vis_sample <- 'Dec_13_2021_Human5'

cur_coords <- subset(anno_df, vis_sample == cur_vis_sample)
cur_seurat <- seurat_obj[,cur_coords$sc_bc]
rownames(cur_coords) <- cur_coords$sc_bc
cur_coords <- cur_coords[colnames(cur_seurat),]

cur_seurat@reductions$spatial <- CreateDimReducObject(
  embeddings = as.matrix(cur_coords[,c('celltrek_1', 'celltrek_2')])
)

p1 <- FeatureEmbedding(
    cur_seurat,
    features = 'scdrs_normscore',
    reduction = 'spatial',
    point_size=1,
    plot_min = 'q0',
    plot_max = 'q100'
  ) + scale_color_gradient2()

pdf(paste0(fig_dir, 'test_scdrs_spatial.pdf'), width=5, height=5)
p1
dev.off()

```



Plot some examples of the co-embedding Seurat objects:
```{r eval=FALSE}

dir.create(paste0(fig_dir, 'umap_coembed'))

human_cp <- c(
      "L1" = "#8B3D5A", "L2/3" = "#E7BDE1", "L3/4" = "#E6A4CD",
      "L3/4/5" = "#CF8BA3", "L5/6" = "#9E6D7F", "L6b" = "#CDAEB9", "WM1" = "#64BCDB", "WM2" = "#62A7D7", "WM3" = "#99C8D7")


st_color_df <- data.frame(
  colour = as.character(human_cp),
  group = names(human_cp)
)
st_color_df$group <- factor(as.character(st_color_df$group), levels=names(human_cp))

file_list <- dir(data_dir)

sc_samples <- c('ADDS_humAD-97', 'ADDS_86')

coembed_files <- paste0('data/vis_', human_rep_samples, '-sc_', sc_samples,'_coembed.rds')


# for(i in 1:length(human_rep_samples)){
for(cur_file in coembed_files){

  #print(i)
  #cur_file_list <- paste0(data_dir, file_list[grepl(human_rep_samples[i], file_list)])
  #cur_file <- cur_file_list[1]

  cur_seurat <- readRDS(cur_file)


  table(cur_seurat$type)

  table(cur_seurat$annotation)
  table(cur_seurat$cell_identity)


  st_sc_group_levels <- c(group_levels, names(human_cp))
  st_sc_color_df <- rbind(color_df, st_color_df)

  cur_seurat$plot_groups <- ifelse(
    cur_seurat$type == 'st',
    as.character(cur_seurat$annotation),
    as.character(cur_seurat$cell_identity)
  )
  cur_seurat$plot_groups <- factor(as.character(cur_seurat$plot_groups), levels=st_sc_group_levels)



  plot_list <- PlotEmbedding(
    cur_seurat,
    group.by = 'plot_groups',
    split.by = 'type',
    plot_under=TRUE,
    raster_dpi = 500,
    raster_scale=0.5, point_size=1,
    color_df = st_sc_color_df,
    label=TRUE,
    plot_theme = umap_theme() + NoLegend()
  )

  outfile <- gsub('data/', '', cur_file)
  outfile <- gsub('.rds', '.pdf', outfile)

  pdf(paste0(fig_dir, 'umap_coembed/labeled_', outfile), height=5, width=10)
  print(wrap_plots(plot_list, ncol=2))
  dev.off()

}


```

plot single-cell data split by sample

```{r eval=FALSE}

plot_list <- PlotEmbedding(
  seurat_obj,
  group.by = 'cell_identity',
  split.by = 'Sample',
  plot_under=TRUE,
  raster_dpi = 500,
  raster_scale=0.5, point_size=1,
  color_df = color_df,
  label=FALSE,
  plot_theme = umap_theme() + NoLegend()
)

pdf(paste0(fig_dir, 'umap_split_samples.pdf'), height=15, width=15)
wrap_plots(plot_list[1:8], ncol=3)
dev.off()

unique(seurat_obj$Sample)[1:8]

subset(seurat_obj@meta.data, Sample == 'ADDS_humAD-97') %>% head
subset(seurat_obj@meta.data, Sample == 'ADDS_86') %>% head


```

Plot all mapped cells in representative samples

```{r eval=FALSE}

ex_neurons <- c(
  'EX L2', 'EX L2-3', 'EX L3-5', 'EX L5', 'EX L5-6', 'EX L6')

inh_neurons <- c(
  'INH VIP+', 'INH', 'INH LAMP5+', 'INH PVALB+', 'INH SST+')

glia <- c(
  'ASC1', 'ASC2', 'ASC3', 'ASC4',
  'MG1', 'MG2',
  'ODC1', 'ODC2', 'ODC3',
  'OPC1', 'OPC2', 'OPC3'
)
vasc <- c(
  'END Arterial', 'END Capillary',
  'T-Pericyte', 'M-Pericyte', 'SMC',
  'Perivascular Fibroblast', 'Meningeal Fibroblast'
)

group_list <- list(
  EX = ex_neurons,
  INH = inh_neurons,
  glia = glia,
  VASC = vasc
)

# get sc coordinates for the current visium sample
plot_list <- list()
for(i in 1:length(human_rep_samples)){

  cur_vis_sample <- human_rep_samples[i]
  print(cur_vis_sample)
  plot_list <- list()
  for(cur_group in names(group_list)){
    cur_coords <- subset(anno_df, vis_sample == cur_vis_sample & cell_identity %in% group_list[[cur_group]])

    # plot the main dataset
    p <- cur_coords %>%
      ggplot(aes(x=celltrek_1, y=celltrek_2, color=cell_identity)) +
      ggrastr::rasterise(geom_point(size=1, alpha=1), dpi=300, scale=0.5) +
      scale_color_manual(values=cp) +
      umap_theme() + coord_fixed() +
      guides(colour = guide_legend(override.aes = list(size=5))) +
      NoLegend()

    plot_list[[cur_group]] <- p
  }

  pdf(paste0(fig_dir, 'rep_samples_mapped/', human_rep_samples[i],'.pdf'), width=12, height=3)
  print(wrap_plots(plot_list, ncol=4))
  dev.off()

}

pdf(paste0(fig_dir, 'rep_samples_mapped_cell_ids.pdf'), width=18, height=3)
print(wrap_plots(plot_list, ncol=8))
dev.off()


```


Plot expression of marker genes in mapped cells

```{r eval=FALSE}

ex_neurons <- c(
  'EX L2', 'EX L2-3', 'EX L3-5', 'EX L5', 'EX L5-6', 'EX L6')

inh_neurons <- c(
  'INH VIP+', 'INH', 'INH LAMP5+', 'INH PVALB+', 'INH SST+')

glia <- c(
  'ASC1', 'ASC2', 'ASC3', 'ASC4',
  'MG1', 'MG2',
  'ODC1', 'ODC2', 'ODC3',
  'OPC1', 'OPC2', 'OPC3'
)
vasc <- c(
  'END Arterial', 'END Capillary',
  'T-Pericyte', 'M-Pericyte', 'SMC',
  'Perivascular Fibroblast', 'Meningeal Fibroblast'
)

group_list <- list(
  EX = ex_neurons,
  INH = inh_neurons,
  glia = glia,
  VASC = vasc
)

cur_vis_sample <- 'Dec_13_2021_Human8'
cur_vis_sample <- 'Dec_13_2021_Human5'

layer_markers <- list(
  'Layer 1' = c('C4or31', 'RELN', 'INPP4B'),
  'Layer 1/2' = c('CHRNA7', 'CNR1', 'CXCL14'),
  'Layer 2' = c('PVRL3', 'RASGRF2', 'WFS1', 'C1QL2', 'CARTPT'),
  'Layer 2/3' = c('GSG1L', 'IGSF11', 'KCNIP2', 'C20orf103', 'CALB1'),
  'Layer 3' = c('PRSS12', 'MFGE8', 'SV2C'),
  'Layer 4' = c('RORB', 'CACNG5', 'CHRNA3', 'KCNIP1', 'PDYN'),
  'Layer 5' = c('VAT1L', 'HTR2C'),
  'Layer 5/6' = c('CPNE7', 'ETV1', 'TOX', 'B3GALT2', 'KCNK2', 'PCP4', 'PDE1A', 'RPRM', 'PCDH20'),
  'Layer 6' = c('FOXP2', 'NTNG2', 'SYT10', 'SYT6', 'TH', 'TMEM163', 'AKR1C2', 'AKR1C3', 'NPY2R', 'OPRK1', 'SEMA3C', 'SYNPR'),
  'Layer 6/6B' = c('GABRA5', 'TLE4', 'PCDH17'),
  'Layer 6B/WM' = c('ADRA2A', 'CTGF'),
  'WM' = c('MBP', 'MOG', 'PLP1')
)

cur_coords <- subset(anno_df, vis_sample == cur_vis_sample)
cur_seurat <- seurat_obj[,cur_coords$sc_bc]
rownames(cur_coords) <- cur_coords$sc_bc
cur_coords <- cur_coords[colnames(cur_seurat),]

cur_seurat@reductions$spatial <- CreateDimReducObject(
  embeddings = as.matrix(cur_coords[,c('celltrek_1', 'celltrek_2')])
)

for(cur_gene in unlist(layer_markers)){

  print(cur_gene)

  if(!(cur_gene %in% rownames(cur_seurat))){
    next
  }
  if(!(cur_gene %in% rownames(seurat_vis))){
    next
  }
 
  p1 <- FeatureEmbedding(
    cur_seurat,
    features = cur_gene,
    reduction = 'spatial',
    point_size=1,
    plot_min = 'q0',
    plot_max = 'q100'
  )

  p2 <- SampleFeaturePlot(
          seurat_vis,
          feature=cur_gene,
          samples_to_plot = cur_vis_sample,
          sample_labels = c("Diagnosis", "Sex", 'Age'),
          ncol = 1,
          raster=TRUE,
          plot_max = 'q100',
          plot_min = 'q0',
          colfunc = inferno,
          rev_colors=TRUE,
          dpi=400,
        )


  pdf(paste0(fig_dir, 'spatial_featureplots/',cur_vis_sample, '-', cur_gene,'.pdf'), width=8, height=4)
  print(p2 | p1)
  dev.off()

}





# get sc coordinates for the current visium sample
plot_list <- list()
for(i in 1:length(human_rep_samples)){

  cur_vis_sample <- human_rep_samples[i]
  print(cur_vis_sample)
  plot_list <- list()
  for(cur_group in names(group_list)){
    cur_coords <- subset(anno_df, vis_sample == cur_vis_sample & cell_identity %in% group_list[[cur_group]])

    # plot the main dataset
    p <- cur_coords %>%
      ggplot(aes(x=celltrek_1, y=celltrek_2, color=cell_identity)) +
      ggrastr::rasterise(geom_point(size=1, alpha=1), dpi=300, scale=0.5) +
      scale_color_manual(values=cp) +
      umap_theme() + coord_fixed() +
      guides(colour = guide_legend(override.aes = list(size=5))) +
      NoLegend()

    plot_list[[cur_group]] <- p
  }

  pdf(paste0(fig_dir, 'rep_samples_mapped/', human_rep_samples[i],'.pdf'), width=12, height=3)
  print(wrap_plots(plot_list, ncol=4))
  dev.off()

}

pdf(paste0(fig_dir, 'rep_samples_mapped_cell_ids.pdf'), width=18, height=3)
print(wrap_plots(plot_list, ncol=8))
dev.off()


```
