#!/bin/bash
#SBATCH --job-name=sr-5XFAD     ## Name of the job.
#SBATCH -p standard          ## partition/queue name
#SBATCH -A vswarup_lab           ## partition/queue name
#SBATCH --nodes=1            ## (-N) number of nodes to use
#SBATCH --ntasks=1          ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=16    ## number of cores the job needs
#SBATCH --error=slurm-%J.err
#SBATCH --mem 64G
#SBATCH --array=2
#SBATCH --time=72:00:00

# move to the desired output directory
cd /dfs3b/swaruplab/smorabit/data/ADDS_2021/visium/October_2021/spaceranger_count/

# set directory for fastqs and images:
fastqs="/dfs3b/swaruplab/smorabit/data/ADDS_2021/visium/October_2021/fastqs/"
align_dir="/dfs3b/swaruplab/smorabit/data/ADDS_2021/visium/October_2021/alignment/"
image_dir="/dfs3b/swaruplab/smorabit/data/ADDS_2021/visium/October_2021/images/"

# list files and get all sample names
fastq_files=($(ls $fastqs))
align_files=($(ls $align_dir))
image_files=($(ls $image_dir))
samples=($(ls $fastqs | cut -d '_' -f 1 | uniq))

# index based on task ID
let index="$SLURM_ARRAY_TASK_ID"

# get sample based on index:
sample=${samples[$index]}
align=${align_files[$index]}
image=${image_files[$index]}
echo $sample
echo $align
echo $image

# manually override the image for the sample that we
image="3_V10D07-124_C1_fiducials.jpg"

# get the image, slide, and area corresponding to this sample
slide=$(echo $image | cut -d '_' -f 2)
area=$(echo $image | cut -d '_' -f 3 | cut -d '.' -f 1)

echo $slide
echo $area

# run spaceranger
transcriptome="/dfs3b/swaruplab/smorabit/resources/spaceranger_reference/refdata-gex-GRCh38-2020-A"
~/swaruplab/smorabit/bin/software/spaceranger-1.3.0/spaceranger count \
                       --id=$sample \
                       --transcriptome=$transcriptome \
                       --fastqs=$fastqs \
                       --sample=$sample \
                       --colorizedimage=$image_dir$image \
                       --slide=$slide \
                       --area=$area \
                       --loupe-alignment=$align_dir$align \
                       --localcores=16 \
                       --localmem=64
