#!/bin/bash
#SBATCH --job-name=split
#SBATCH -p standard
#SBATCH -A mblurton_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --error=slurm-%J.err
#SBATCH --mem 200G
#SBATCH --array=1-8
#SBATCH --time=72:00:00

# conda init bash
# conda activate splitseq

# activate conda env:
source ~/.bashrc
conda activate splitseq

module load samtools
module load star

# move to fire mouse directory
cd /dfs3b/swaruplab/smorabit/data/ADDS_2021/

# set data and reference directories
fastqs="./expdata/Batch3/"
ref_dir="./genomes/hg38/"

let index="$SLURM_ARRAY_TASK_ID"

# find current sublibrary
sublibraries=($(ls $fastqs | cut -d '_' -f 1-3 | uniq))
sample=${sublibraries[$index]}
echo $sample

# make output dir for this sample
mkdir ./analysis/Batch3/$sample

splitpipe/split-pipe \
  --mode all \
  --nthreads 32 \
  --genome_dir $ref_dir \
  --fq1 $fastqs$sample"_L003_R1_001.fastq.gz" \
  --fq2 $fastqs$sample"_L003_R2_001.fastq.gz" \
  --output_dir analysis/Batch3/$sample \
  --sample humAD-86 A1-A2 \
  --sample 19 A3-A4 \
  --sample 64 A5-A6 \
  --sample 121 A7-A8 \
  --sample humAD-99 A9-A10 \
  --sample 68 A11-A12 \
  --sample humAD-98 B1-B2 \
  --sample 107 B3-B4 \
  --sample 62 B5-B6 \
  --sample 95 B7-B8 \
  --sample 60 B9-B10 \
  --sample humAD-87 B11-B12 \
  --sample 11 C1-C2 \
  --sample 118 C3-C4 \
  --sample 98 C5-C6 \
  --sample 56 C7-C8 \
  --sample 18 C9-C10 \
  --sample 109 C11-C12 \
  --sample 29 D1-D2 \
  --sample 48 D3-D4 \
  --sample 122 D5-D6 \
  --sample 79 D7-D8 \
  --sample 49 D9-D10 \
  --sample 111 D11-D12 \
