
Load ADDS Seurat data:

```{r eval=FALSE}
# conda activate cicero

library(Seurat)
library(tidyverse)
library(cowplot)
library(Matrix)
library(viridis)
library(harmony)
library(ggpubr)
library(patchwork)
library(RColorBrewer)
library(ggrepel)

theme_set(theme_cowplot())
colfunc <- colorRampPalette(rev(brewer.pal(9, 'Purples' )[2:9]))
setwd("/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/")

# directories
data_dir <- "data/"
fig_dir <- 'figures/'

umap_theme <- theme(
  axis.line=element_blank(),
  axis.text.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks=element_blank(),
  axis.title.x=element_blank(),
  axis.title.y=element_blank(),
  panel.background=element_blank(),
  panel.border=element_blank(),
  panel.grid.major=element_blank(),
  panel.grid.minor=element_blank(),
  plot.background=element_blank(),
  plot.title=element_text(hjust=0.5)
)

# re-load the current seurat object:
seurat_obj <- readRDS("/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/data/ADDS_integrated_scvi.rds")

```

Make a new Seurat object with just the FC

```{r eval=FALSE}

s_obj <- subset(seurat_obj, Region == 'FCX')
saveRDS(s_obj, "/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/data/ADDS_integrated_scvi_FCX.rds")

```

Combine individual DEG tables into one big table:

```{r eval=FALSE}

# DEGs for clusters
DEG_dir <- "/dfs7/swaruplab/smorabit/analysis/ADDS_2021/splitseq/DEGs/cluster_markers/"
DEG_tests <- dir(DEG_dir)

# combine  all tests into one table:
combined <- Reduce(rbind, lapply(dir(DEG_dir), function(file){
  read.csv(paste0(DEG_dir, file))
}))

# write full table
write.csv(combined, file=paste0('DEGs/data/cluster_markers.csv'), quote=FALSE, row.names=FALSE)

```

Make marker gene heatmap:

```{r eval=FALSE}

# read combined
degs <- read.csv(paste0('DEGs/data/cluster_markers.csv'))
degs$group <- factor(
  degs$group,
  levels = 1:15
)


n_degs <- 5
plot_genes <- degs %>%
  arrange(group) %>%
  subset(p_val_adj <= 0.05) %>%
  group_by(group) %>%
  top_n(n_degs, wt=avg_log2FC)  %>%
  .$gene


# set random seed
set.seed(42)

seurat_obj$barcode <- colnames(seurat_obj)
temp <- table(seurat_obj@meta.data$bs.q15)

df <- data.frame()
for(i in 1:length(temp)){

  if(temp[[i]] < 500){
    cur_df <- seurat_obj@meta.data %>% subset(bs.q15 == names(temp)[i])
  } else{
    cur_df <- seurat_obj@meta.data %>% subset(bs.q15 == names(temp)[i]) %>% sample_n(500)
  }
  df <- rbind(df, cur_df)
}

p <- DoHeatmap(
  seurat_obj %>% subset(barcode %in% df$barcode),
  features=unlist(plot_genes),
  group.by='bs.q15',
  raster=TRUE, slot='scale.data'
) + theme(
  axis.text.y = element_text(face='italic')
) + NoLegend()

pdf(paste0(fig_dir, 'marker_gene_heatmap.pdf'), width=12, height=12, useDingbats=FALSE)
p
dev.off()

```


cluster marker gene dotplots:

```{r eval=FALSE}

degs <- read.csv(paste0('DEGs/data/cluster_markers.csv'))
degs$group <- factor(
  degs$group,
  levels = 1:15
)

clusters <- 'bs.q15'
name <- 'cluster_markers'

################################################################################
# Dot Plot of top 20 genes
################################################################################
library(RColorBrewer)

dir.create(paste0(fig_dir, name))
dir.create(paste0(fig_dir, name, '/dotplots/'))

colfunc <- colorRampPalette(c(rev(brewer.pal(9, 'Purples' )[2:9]), 'white'))


for(cur_group in unique(degs$group)){

  print(cur_group)
  genes <- degs %>% subset(group == cur_group) %>% top_n(20, wt=avg_log2FC) %>% .$gene


  # dimplot highlighting the current group:
  umap_plot <- DimPlot(seurat_obj,group.by=clusters, cells.highlight=colnames(seurat_obj)[seurat_obj@meta.data[,clusters] == cur_group], label=TRUE) + NoLegend() + umap_theme+  ylab('') + xlab('') + ggtitle('')

  p <- DotPlot(seurat_obj, features=genes, group.by=clusters, dot.min=0.15 ) +
    RotatedAxis() +
      scale_color_gradientn(
      colors=rev(colfunc(256)),
      guide = guide_colorbar(barwidth=0.5, barheight=20, ticks=FALSE, label=FALSE)
  ) +
    ylab('') + xlab('')

  pdf(paste0(fig_dir, name, '/dotplots/', gsub(' ', '_',  cur_group), '_top_genes.pdf'), width=12, height=6, useDingbats=FALSE)
  patch <- umap_plot + p + plot_layout(widths=c(1,2))
  print(patch)
  dev.off()
}


```

Select representative samples to plot

From Emily:

4mo = slide 2 A1 (V111A06-322_A1_crop.nd2)
6mo = slide 15 A1 (V11A06-320_A1_crop.nd2)
8mo = slide 19 A1 (V11A06-320_A1_crop.nd2)
12mo = slide 16  (V11A13-386_C1_crop.nd2)

```{r eval=FALSE}


table(seurat_obj$SAMPLE, seurat_obj$Condition)
> table(seurat_obj$SAMPLE, seurat_obj$Condition)



markers <- c('Csf1r', 'Aqp4', 'Mobp', 'Pdgfra', 'Slc17a7', 'Gad2')


pdf(paste0(fig_dir, 'marker_genes.pdf'), width=12, height=8, useDingbats=FALSE)
for(gene in markers){

  p1 <- FeaturePlot(seurat_obj, features=gene, max.cutoff='q99', order=TRUE) +
    scale_color_gradientn(colors=colfunc(256), guide = guide_colorbar(barwidth=15, barheight=0.5, ticks=FALSE)) +
    umap_theme + theme(legend.position='bottom')

  plot_list <- list()
  for(sample in unique(seurat_obj$SampleID)){
    cur <- subset(seurat_obj, SampleID == sample)
    cur_condition <- as.character(unique(cur$Condition))
    cur_image <- names(cur@images)[sapply(names(cur@images), function(x){nrow(cur@images[[x]]@coordinates) > 0})]
    cur@images <- list(cur_image = cur@images[[cur_image]])
    plot_list[[sample]] <- SpatialFeaturePlot(cur, features=gene) + NoLegend() +
      ggtitle(paste0(sample, ' (',cur_condition, ')'))
  }
  print(p1 | wrap_plots(plot_list, ncol=2) + plot_layout(widths=c(1,1)))
}
dev.off()

```
